In [2]:
import tensorflow as tf
tf.test.is_gpu_available()

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


True

In [4]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [5]:
import tensorflow as tf
from tensorflow import keras
from keras.preprocessing import image
from keras.layers import GlobalMaxPool2D
from keras.applications.resnet import ResNet50, preprocess_input


In [6]:
model= ResNet50(weights='imagenet', include_top=False, input_shape=(224, 224, 3))
model.trainable= False

94765736/94765736 [==============================] - 115s 1us/step


In [7]:
model= keras.Sequential([
    model,
    GlobalMaxPool2D()
])

In [8]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 resnet50 (Functional)       (None, 7, 7, 2048)        23587712  
                                                                 
 global_max_pooling2d (Globa  (None, 2048)             0         
 lMaxPooling2D)                                                  
                                                                 
Total params: 23,587,712
Trainable params: 0
Non-trainable params: 23,587,712
_________________________________________________________________


## **Demo**

In [12]:
import tensorflow as tf

In [14]:
from tensorflow.keras.preprocessing import image


In [15]:
img= image.load_img('img.jpg', target_size= (224, 224))

In [21]:
img_array= image.img_to_array(img)
img_array.shape

(224, 224, 3)

In [22]:
import numpy as np
expanded_image_array= np.expand_dims(img_array, axis=0)
expanded_image_array.shape

(1, 224, 224, 3)

In [23]:
processed_img= preprocess_input(expanded_image_array)
processed_img.shape

(1, 224, 224, 3)

In [25]:
y_hat= model.predict(processed_img)
y_hat

1/1 [==============================] - 0s 32ms/step


array([[ 4.94419 , 29.569649,  0.      , ...,  4.027456,  8.034949,
        14.602846]], dtype=float32)

In [26]:
y_hat.shape

(1, 2048)

In [28]:
y_hat= y_hat.flatten()
y_hat.shape

(2048,)

In [29]:
y_hat

array([ 4.94419 , 29.569649,  0.      , ...,  4.027456,  8.034949,
       14.602846], dtype=float32)

In [30]:
# L2 Norm ---> sqrt of summation of squares
np.sqrt(np.dot(y_hat, y_hat))

260.19556

In [31]:
from numpy.linalg import norm
norm(y_hat)

260.19556

In [32]:
y_hat/norm(y_hat)

array([0.01900182, 0.11364394, 0.        , ..., 0.01547857, 0.03088043,
       0.05612258], dtype=float32)

In [43]:
def extract_features(img_path, model):
    img = image.load_img(img_path, target_size=(224, 224))
    image_array = image.img_to_array(img)
    expanded_image_array = np.expand_dims(image_array, axis=0)
    processed_img = preprocess_input(expanded_image_array)
    y_hat = model.predict(processed_img)
    features = y_hat.flatten()
    normalized_features = features/norm(features)
    return normalized_features


In [44]:
extract_features('img.jpg', model)

1/1 [==============================] - 0s 33ms/step


array([0.01900182, 0.11364394, 0.        , ..., 0.01547857, 0.03088043,
       0.05612258], dtype=float32)

In [ ]:
import os
os.listdir('images') # all the filenames in the images folder

In [37]:
filenames= []

for filename in os.listdir('images'):
    filenames.append(os.path.join('images', filename))


In [38]:
len(filenames)

44441

In [39]:
filenames[:5]

['images\\10000.jpg',
 'images\\10001.jpg',
 'images\\10002.jpg',
 'images\\10003.jpg',
 'images\\10004.jpg']

In [47]:
from tqdm import tqdm

In [ ]:
feature_list= []

for filename in tqdm(filenames):
    feature_list.append(extract_features(filename, model))


In [ ]:
import pickle
pickle.dump(feature_list, open('embeddings.pkl', 'wb'))
pickle.dump(filenames, open('filenames.pkl', 'wb'))

<a href="demo.MP4" title="Link Title"><img src="image.png" alt="Alternate Text" /></a>

[![Alternate Text](image.png)](demo.MP4 "Link Title")

<video width="1080" height="720" controls>
  <source src="demo.MP4" type="video/mp4">
</video>

<iframe width="560" height="315" src="https://github.com/ideepankarsharma2003/ProductRecommendationSystem/blob/main/demo.MP4" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

## Demo

<iframe width="560" height="315" src="https://youtu.be/N1UMycRJbAw" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
